// <auto-generated />
using Melodee.Common.Models.SearchEngines.ArtistSearchEngineServiceData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Melodee.Common.Migrations.ArtistSearchEngine
{
    [DbContext(typeof(ArtistSearchEngineServiceDbContext))]
    [Migration("20260622224939_InitialArtistSearchEngineSchema")]
    partial class InitialArtistSearchEngineSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Melodee.Common.Models.SearchEngines.ArtistSearchEngineServiceData.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlbumType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtistId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("MusicBrainzId")
                        .HasColumnType("UUID");

                    b.Property<byte[]>("MusicBrainzReleaseGroupId")
                        .HasColumnType("UUID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameNormalized")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SortName")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpotifyId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId", "NameNormalized", "Year");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("Melodee.Common.Models.SearchEngines.ArtistSearchEngineServiceData.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlternateNames")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("AmgId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscogsId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItunesId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastFmId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastRefreshed")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("MusicBrainzId")
                        .HasColumnType("UUID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameNormalized")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SortName")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpotifyId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("WikiDataId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AmgId")
                        .IsUnique();

                    b.HasIndex("DiscogsId")
                        .IsUnique();

                    b.HasIndex("ItunesId")
                        .IsUnique();

                    b.HasIndex("LastFmId")
                        .IsUnique();

                    b.HasIndex("MusicBrainzId")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.HasIndex("NameNormalized");

                    b.HasIndex("SortName");

                    b.HasIndex("SpotifyId")
                        .IsUnique();

                    b.HasIndex("WikiDataId")
                        .IsUnique();

                    b.HasIndex("IsLocked", "LastRefreshed");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("Melodee.Common.Models.SearchEngines.ArtistSearchEngineServiceData.ArtistAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtistId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameNormalized")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NameNormalized");

                    b.HasIndex("ArtistId", "NameNormalized")
                        .IsUnique();

                    b.ToTable("ArtistAliases", (string)null);
                });

            modelBuilder.Entity("Melodee.Common.Models.SearchEngines.ArtistSearchEngineServiceData.Album", b =>
                {
                    b.HasOne("Melodee.Common.Models.SearchEngines.ArtistSearchEngineServiceData.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("Melodee.Common.Models.SearchEngines.ArtistSearchEngineServiceData.ArtistAlias", b =>
                {
                    b.HasOne("Melodee.Common.Models.SearchEngines.ArtistSearchEngineServiceData.Artist", "Artist")
                        .WithMany("Aliases")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("Melodee.Common.Models.SearchEngines.ArtistSearchEngineServiceData.Artist", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("Aliases");
                });
#pragma warning restore 612, 618
        }
    }
}
