services:
  melodee-db:
    image: docker.io/library/postgres:17
    environment:
      POSTGRES_DB: melodeedb
      POSTGRES_USER: melodeeuser
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGUSER: melodeeuser
    volumes:
      - melodee-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  melodee.blazor:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - melodee-db
    environment:
      - ConnectionStrings__DefaultConnection=Host=melodee-db;Port=5432;Database=melodeedb;Username=melodeeuser;Password=${DB_PASSWORD}
    volumes:
      - ${STORAGE_VOLUME}:/app/storage
      - ${INBOUND_VOLUME}:/app/inbound
      - ${STAGING_VOLUME}:/app/staging
      - ${USER_IMAGES_VOLUME}:/app/user-images
      - ${PLAYLISTS_VOLUME}:/app/playlists
    ports:
      - "${MELODEE_PORT}:8080"
    restart: unless-stopped

volumes:
  melodee-db-data:          # Named volume for database persistence
  melodee-storage:          # For processed music library
  melodee-inbound:          # For incoming music files
  melodee-staging:          # For staging area
  melodee-user-images:      # For user profile images
  melodee-playlists:        # For playlist data
