name: melodee

services:
  melodee-db:
    image: docker.io/library/postgres:17
    environment:
      POSTGRES_DB: melodeedb
      POSTGRES_USER: melodeeuser
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGUSER: melodeeuser
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  melodee.blazor:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - melodee-db
    environment:
      - ConnectionStrings__DefaultConnection=Host=melodee-db;Port=5432;Database=melodeedb;Username=melodeeuser;Password=${DB_PASSWORD};Pooling=true;MinPoolSize=10;MaxPoolSize=50;SSL Mode=Disable;Include Error Detail=true;
      - ConnectionStrings__MusicBrainzConnection=/app/storage/_search-engines/musicbrainz/musicbrainz.db,
      - ConnectionStrings__ArtistSearchEngineConnection=Data Source=/app/storage/_search-engines/artistSearchEngine.db;Cache=Shared;
    volumes:
      - storage:/app/storage
      - inbound:/app/inbound
      - staging:/app/staging
      - user_images:/app/user-images
      - playlists:/app/playlists
    ports:
      - "${MELODEE_PORT}:8080"
    restart: unless-stopped

volumes:
  db_data:
    name: melodee_db_data
  storage:
    name: melodee_storage
  inbound:
    name: melodee_inbound
  staging:
    name: melodee_staging
  user_images:
    name: melodee_user_images
  playlists:
    name: melodee_playlists
