services:
  melodee-db:
    image: docker.io/library/postgres:17
    environment:
      POSTGRES_DB: melodeedb
      POSTGRES_USER: melodeeuser
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGUSER: melodeeuser
    volumes:
      - melodee_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  melodee.blazor:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - melodee-db
    environment:
      - ConnectionStrings__DefaultConnection=Host=melodee-db;Port=5432;Database=melodeedb;Username=melodeeuser;Password=${DB_PASSWORD}
    volumes:
      - melodee_storage:/app/storage
      - melodee_inbound:/app/inbound
      - melodee_staging:/app/staging
      - melodee_user_images:/app/user-images
      - melodee_playlists:/app/playlists
    ports:
      - "${MELODEE_PORT}:8080"
    restart: unless-stopped

volumes:
  melodee_db_data:
    external: true
  melodee_storage:
    external: true
  melodee_inbound:
    external: true
  melodee_staging:
    external: true
  melodee_user_images:
    external: true
  melodee_playlists:
    external: true
