<Project ToolsVersion="15.0">
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageFloatingVersionsEnabled>true</CentralPackageFloatingVersionsEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Ardalis.GuardClauses" Version="*" />
    <PackageVersion Include="Asp.Versioning.Http" Version="*" />
    <PackageVersion Include="Asp.Versioning.Mvc" Version="*" />
    <PackageVersion Include="Asp.Versioning.Mvc.ApiExplorer" Version="*" />
    <PackageVersion Include="AuralizeBlazor" Version="*" />
    <PackageVersion Include="BCrypt.Net-Next" Version="*" />
    <PackageVersion Include="Blazor.Bootstrap" Version="*" />
    <PackageVersion Include="Blazored.SessionStorage" Version="*" />
    <PackageVersion Include="ChoETL" Version="*" />
    <PackageVersion Include="coverlet.collector" Version="*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageVersion>
    <PackageVersion Include="Crc32.NET" Version="*" />
    <PackageVersion Include="CsvHelper" Version="*" />
    <PackageVersion Include="Dapper" Version="*" />
    <PackageVersion Include="DecentDB.EntityFrameworkCore" Version="*" />
    <PackageVersion Include="DecentDB.EntityFrameworkCore.Design" Version="*" />
    <PackageVersion Include="DecentDB.EntityFrameworkCore.NodaTime" Version="*" />
    <PackageVersion Include="Fastenshtein" Version="*" />
    <PackageVersion Include="FbNetExternalEngine.Integration" Version="*" />
    <PackageVersion Include="FFMpegCore" Version="*" />
    <PackageVersion Include="FluentAssertions" Version="*" />
    <PackageVersion Include="FluentValidation" Version="*" />
    <PackageVersion Include="Hashids.net" Version="*" />
    <PackageVersion Include="Hqub.Last.fm" Version="*" />
    <PackageVersion Include="HtmlAgilityPack" Version="*" />
    <PackageVersion Include="IdGen" Version="*" />
    <PackageVersion Include="IdSharp.Common" Version="*" />
    <PackageVersion Include="IdSharp.Tagging" Version="*" />
    <PackageVersion Include="JetBrains.Annotations" Version="*" />
    <PackageVersion Include="Jint" Version="*" />
    <PackageVersion Include="K4os.Hash.xxHash" Version="*" />
    <PackageVersion Include="LiteDB" Version="*" />
    <PackageVersion Include="Mapster" Version="*" />
    <PackageVersion Include="Markdig" Version="*" />
    <PackageVersion Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="*" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="*" />
    <PackageVersion Include="Microsoft.AspNetCore.Http" Version="*" />
    <PackageVersion Include="Microsoft.AspNetCore.Http.Abstractions" Version="*" />
    <PackageVersion Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="*" />
    <PackageVersion Include="Microsoft.AspNetCore.WebUtilities" Version="*" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="*" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="*" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="*" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="*" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.Abstractions" Version="*" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageVersion>
    <PackageVersion Include="Microsoft.EntityFrameworkCore.InMemory" Version="*" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageVersion>
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="*" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="*" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.FileExtensions" Version="*" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="*" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="*" />
    <PackageVersion Include="Microsoft.IdentityModel.Tokens" Version="*" />
    <PackageVersion Include="Microsoft.Net.Http.Headers" Version="*" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="*" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="*" />
    <PackageVersion Include="MailKit" Version="*" />
    <PackageVersion Include="MimeKit" Version="*" />
    <PackageVersion Include="MimeTypes" Version="*" />
    <PackageVersion Include="Moq" Version="*" />
    <PackageVersion Include="NAudio" Version="*" />
    <PackageVersion Include="Newtonsoft.Json" Version="*" />
    <PackageVersion Include="NodaTime" Version="*" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="*" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL.NodaTime" Version="*" />
    <PackageVersion Include="Polly" Version="*" />
    <PackageVersion Include="Polly.Core" Version="*" />
    <PackageVersion Include="PSC.Blazor.Components.MarkdownEditor" Version="*" />
    <PackageVersion Include="Quartz.AspNetCore" Version="*" />
    <PackageVersion Include="Quartz.Extensions.DependencyInjection" Version="*" />
    <PackageVersion Include="Quartz.Jobs" Version="*" />
    <PackageVersion Include="Quartz.Plugins.TimeZoneConverter" Version="*" />
    <PackageVersion Include="Quartz.Serialization.SystemTextJson" Version="*" />
    <PackageVersion Include="Radzen.Blazor" Version="*" />
    <PackageVersion Include="Rebus" Version="*" />
    <PackageVersion Include="Rebus.ServiceProvider" Version="*" />
    <PackageVersion Include="Serilog" Version="*" />
    <PackageVersion Include="Serilog.AspNetCore" Version="*" />
    <PackageVersion Include="Serilog.Formatting.Compact" Version="*" />
    <PackageVersion Include="Serilog.Settings.AppSettings" Version="*" />
    <PackageVersion Include="Serilog.Settings.Configuration" Version="*" />
    <PackageVersion Include="Serilog.Sinks.Console" Version="*" />
    <PackageVersion Include="Serilog.Sinks.File" Version="*" />
    <PackageVersion Include="SerilogTimings" Version="*" />
    <PackageVersion Include="Scalar.AspNetCore" Version="*" />
    <PackageVersion Include="SharpZipLib" Version="*" />
    <PackageVersion Include="SixLabors.ImageSharp" Version="*" />
    <PackageVersion Include="SmartFormat" Version="*" />
    <PackageVersion Include="Spectre.Console" Version="*" />
    <PackageVersion Include="Spectre.Console.Cli" Version="*" />
    <PackageVersion Include="Spectre.Console.Json" Version="*" />
    <PackageVersion Include="SpotifyAPI.Web" Version="*" />
    <PackageVersion Include="Sqids" Version="*" />
    <PackageVersion Include="System.IdentityModel.Tokens.Jwt" Version="*" />
    <PackageVersion Include="System.IO.Hashing" Version="*" />
    <PackageVersion Include="System.Linq.Dynamic.Core" Version="*" />
    <PackageVersion Include="System.Net.Http" Version="*" />
    <PackageVersion Include="System.Reactive" Version="*" />
    <PackageVersion Include="System.Resources.Extensions" Version="*" />
    <PackageVersion Include="System.ServiceModel.Syndication" Version="*" />
    <PackageVersion Include="Toolbelt.Blazor.HotKeys2" Version="*" />
    <PackageVersion Include="Xamarin.UITest" Version="*" />
    <PackageVersion Include="xunit" Version="*" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageVersion>
    <PackageVersion Include="z440.atl.core" Version="*" />
    <PackageVersion Include="bunit" Version="*" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Testing" Version="*" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.Authorization" Version="*" />
    <PackageVersion Include="Spectre.Console.Testing" Version="*" />
    <PackageVersion Include="BenchmarkDotNet" Version="*" />
    <PackageVersion Include="NBomber" Version="*" />
    <PackageVersion Include="Google.Apis.Auth" Version="*" />
    <PackageVersion Include="NodaTime.Testing" Version="*" />
    <PackageVersion Include="NUnit" Version="*" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Common" Version="*" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="*" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="*" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Workspaces.Common" Version="*" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="*" />
    <PackageVersion Include="HtmlSanitizer" Version="*-*" />
    <PackageVersion Include="AngleSharp" Version="*" />
    <PackageVersion Include="AngleSharp.Css" Version="*-*" />
    <PackageVersion Include="Microsoft.Playwright" Version="*" />
    <PackageVersion Include="Microsoft.Playwright.Xunit" Version="*" />
  </ItemGroup>
</Project>
