<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>Melodee.Tests.OpenSubsonic</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Moq" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="xunit"/>
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Melodee.Blazor\Melodee.Blazor.csproj">
      <ReferenceOutputAssembly>true</ReferenceOutputAssembly>
      <OutputItemType>Reference</OutputItemType>
    </ProjectReference>
    <ProjectReference Include="..\..\src\Melodee.Common\Melodee.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\data\open-subsonic-1.16.1-openapi.json">
      <Link>Data/open-subsonic-1.16.1-openapi.json</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\data\subsonic-rest-api-1.16.1.xsd">
      <Link>Data/subsonic-rest-api-1.16.1.xsd</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <Target Name="CopyDepsFiles" AfterTargets="Build">
    <Copy SourceFiles="..\..\src\Melodee.Blazor\bin\$(Configuration)\$(TargetFramework)\server.deps.json"
          DestinationFolder="$(OutDir)"
          SkipUnchangedFiles="true" />
    <Copy SourceFiles="..\..\src\Melodee.Blazor\bin\$(Configuration)\$(TargetFramework)\server.runtimeconfig.json"
          DestinationFolder="$(OutDir)"
          SkipUnchangedFiles="true" />
  </Target>

</Project>
