ARG DOTNET_ASPNET_IMAGE=mcr.microsoft.com/dotnet/aspnet:10.0
FROM ${DOTNET_ASPNET_IMAGE}

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ffmpeg \
        postgresql-client \
        curl \
        lbzip2 \
        && rm -rf /var/lib/apt/lists/*

COPY scan/publish/ .

ENTRYPOINT ["dotnet", "server.dll"]
